### ISSUE TITLE
web sql: animation doesn't change on cancel

### ISSUE THREAD

**Issue by smacker** [src-d/gitbase-web#352] opened 2019-03-04 17:16 UTC
Simple query with only 2 repositories `engine` and `aws-sdk-php` is running for 7 minutes. That's too long. I killed it. (keep in mind it doesn't run through all HEAD files, gitbase-web adds LIMIT 100)
But the "guy" is still jumping.

<img width="923" alt="screenshot 2019-03-04 at 13 23 56" src="https://user-images.githubusercontent.com/406916/53733872-9bad3080-3e82-11e9-9631-170883dea6c5.png">

**Comment by dpordomingo** [comment] 2019-03-28 08:41
I can not reproduce it with `gitbase-web`, trying with:
- docker version: 1.39
- srcd cli version: v0.11.0
- srcd daemon version: v0.11.0
- srcd/gitbase: v0.19.0
- srcd/gitbase-web: v0.6.2

I tried with ~7k repos and it was properly stoped and the robot also stopped jumping.
How did you try to stop it? with cancel button under the robot?

![image](https://user-images.githubusercontent.com/2437584/55142698-881d7e80-513d-11e9-86d4-21acd559ef96.png)

**Comment by carlosms** [comment] 2019-04-05 10:40
> keep in mind it doesn't run through all HEAD files, gitbase-web adds LIMIT 100
No when it is used from Engine: https://github.com/src-d/engine/blob/master/cmd/srcd-server/engine/web.go#L14

**Comment by carlosms** [comment] 2019-04-05 10:46
I think this must be caused by #357.
The empathy session was done with engine v0.11.0-rc.1, which included gitbase-web 0.6.0. The fix for #357 was included in 0.6.2; shipped with engine v0.11.0 final.

Closing as fixed.

**Closed by carlosms** 2019-04-05 10:46 UTC
Labels: bug, empathy-sessions
